version: 2.1

orbs:
  python: circleci/python@3.3.0
  codecov: codecov/codecov@5   # <-- added

jobs:
  lint_and_test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Upgrade pip
          command: python -m pip install --upgrade pip
      - run:
          name: Install package with dev extras
          command: pip install -e ".[dev]"
      - run:
          name: Run linters
          command: |
            ruff --version
            ruff check .
      - run:
          name: Run tests with coverage (XML + terminal)
          command: |
            pytest -v \
              --cov=qpfolio \
              --cov-report=term-missing \
              --cov-report=xml:coverage.xml
      - codecov/upload:
          file: coverage.xml       # <-- added
          flags: unittests
          verbose: true
      - run:
          name: Build wheel
          command: python -m build

workflows:
  build_and_test:
    jobs:
      - lint_and_test
