version: 2.1

orbs:
  python: circleci/python@3.3.0

jobs:
  lint_and_test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Upgrade pip
          command: python -m pip install --upgrade pip
      - run:
          name: Install package with dev extras
          command: pip install -e ".[dev]"
      - run:
          name: Run linters
          command: |
            ruff --version
            ruff check .
      - run:
          name: Run tests
          command: pytest -v --cov=qpfolio --cov-report=term-missing
      - run:
          name: Build wheel
          command: python -m build

workflows:
  build_and_test:
    jobs:
      - lint_and_test
